# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AntennaTool_V5.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.diagRad = QtWidgets.QWidget()
        self.diagRad.setObjectName("diagRad")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.diagRad)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.diagRad)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.diagRad)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.folderPath = QtWidgets.QLineEdit(self.diagRad)
        self.folderPath.setEnabled(True)
        self.folderPath.setReadOnly(True)
        self.folderPath.setObjectName("folderPath")
        self.verticalLayout_2.addWidget(self.folderPath)
        self.folderPath_4 = QtWidgets.QLineEdit(self.diagRad)
        self.folderPath_4.setReadOnly(True)
        self.folderPath_4.setClearButtonEnabled(False)
        self.folderPath_4.setObjectName("folderPath_4")
        self.verticalLayout_2.addWidget(self.folderPath_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.browseFolder = QtWidgets.QPushButton(self.diagRad)
        self.browseFolder.setObjectName("browseFolder")
        self.verticalLayout_7.addWidget(self.browseFolder)
        self.browseFolder_4 = QtWidgets.QPushButton(self.diagRad)
        self.browseFolder_4.setObjectName("browseFolder_4")
        self.verticalLayout_7.addWidget(self.browseFolder_4)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_freq = QtWidgets.QLabel(self.diagRad)
        self.label_freq.setObjectName("label_freq")
        self.horizontalLayout_2.addWidget(self.label_freq)
        self.cb_frequency_4 = QtWidgets.QComboBox(self.diagRad)
        self.cb_frequency_4.setObjectName("cb_frequency_4")
        self.horizontalLayout_2.addWidget(self.cb_frequency_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_what_plot = QtWidgets.QLabel(self.diagRad)
        self.label_what_plot.setObjectName("label_what_plot")
        self.horizontalLayout_3.addWidget(self.label_what_plot)
        self.cb_what_plot = QtWidgets.QComboBox(self.diagRad)
        self.cb_what_plot.setObjectName("cb_what_plot")
        self.horizontalLayout_3.addWidget(self.cb_what_plot)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.saveCsv = QtWidgets.QPushButton(self.diagRad)
        self.saveCsv.setObjectName("saveCsv")
        self.horizontalLayout_4.addWidget(self.saveCsv)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.diagRad)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.diagRad)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.normalize = QtWidgets.QCheckBox(self.splitter)
        self.normalize.setObjectName("normalize")
        self.hold = QtWidgets.QCheckBox(self.splitter)
        self.hold.setObjectName("hold")
        self.clearBtn_2 = QtWidgets.QPushButton(self.splitter)
        self.clearBtn_2.setObjectName("clearBtn_2")
        self.gridLayout_2.addWidget(self.splitter, 2, 0, 1, 1)
        self.tabWidget.addTab(self.diagRad, "")
        self.dist = QtWidgets.QWidget()
        self.dist.setObjectName("dist")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dist)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_13 = QtWidgets.QLabel(self.dist)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_26.addWidget(self.label_13)
        self.folderPath_2 = QtWidgets.QLineEdit(self.dist)
        self.folderPath_2.setObjectName("folderPath_2")
        self.horizontalLayout_26.addWidget(self.folderPath_2)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.browseFolder_2 = QtWidgets.QPushButton(self.dist)
        self.browseFolder_2.setObjectName("browseFolder_2")
        self.horizontalLayout_25.addWidget(self.browseFolder_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_14 = QtWidgets.QLabel(self.dist)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_27.addWidget(self.label_14)
        self.cb_frequency_2 = QtWidgets.QComboBox(self.dist)
        self.cb_frequency_2.setObjectName("cb_frequency_2")
        self.horizontalLayout_27.addWidget(self.cb_frequency_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_15 = QtWidgets.QLabel(self.dist)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_28.addWidget(self.label_15)
        self.cb_what_plot_2 = QtWidgets.QComboBox(self.dist)
        self.cb_what_plot_2.setObjectName("cb_what_plot_2")
        self.horizontalLayout_28.addWidget(self.cb_what_plot_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_28)
        self.saveCsv_2 = QtWidgets.QPushButton(self.dist)
        self.saveCsv_2.setObjectName("saveCsv_2")
        self.horizontalLayout_5.addWidget(self.saveCsv_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.dist)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_4.addWidget(self.graphicsView_5, 2, 0, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(self.dist)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.normalize_2 = QtWidgets.QCheckBox(self.splitter_4)
        self.normalize_2.setObjectName("normalize_2")
        self.hold_2 = QtWidgets.QCheckBox(self.splitter_4)
        self.hold_2.setObjectName("hold_2")
        self.clearBtn_3 = QtWidgets.QPushButton(self.splitter_4)
        self.clearBtn_3.setObjectName("clearBtn_3")
        self.gridLayout_4.addWidget(self.splitter_4, 3, 0, 1, 1)
        self.tabWidget.addTab(self.dist, "")
        self.perdas = QtWidgets.QWidget()
        self.perdas.setObjectName("perdas")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.perdas)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_16 = QtWidgets.QLabel(self.perdas)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_32.addWidget(self.label_16)
        self.folderPath_3 = QtWidgets.QLineEdit(self.perdas)
        self.folderPath_3.setObjectName("folderPath_3")
        self.horizontalLayout_32.addWidget(self.folderPath_3)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_32)
        self.browseFolder_3 = QtWidgets.QPushButton(self.perdas)
        self.browseFolder_3.setObjectName("browseFolder_3")
        self.horizontalLayout_31.addWidget(self.browseFolder_3)
        self.verticalLayout_17.addLayout(self.horizontalLayout_31)
        self.verticalLayout_16.addLayout(self.verticalLayout_17)
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.perdas)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout_16.addWidget(self.graphicsView_6)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.splitter_5 = QtWidgets.QSplitter(self.perdas)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.verticalLayout_15.addWidget(self.splitter_5)
        self.gridLayout_5.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.perdas, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_freq_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_freq_2.setObjectName("label_freq_2")
        self.verticalLayout_4.addWidget(self.label_freq_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.folderPath_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.folderPath_5.setMinimumSize(QtCore.QSize(81, 0))
        self.folderPath_5.setObjectName("folderPath_5")
        self.verticalLayout_5.addWidget(self.folderPath_5)
        self.folderPath_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.folderPath_6.setMinimumSize(QtCore.QSize(81, 20))
        self.folderPath_6.setObjectName("folderPath_6")
        self.verticalLayout_5.addWidget(self.folderPath_6)
        self.cb_frequency_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_frequency_3.setMinimumSize(QtCore.QSize(81, 20))
        self.cb_frequency_3.setObjectName("cb_frequency_3")
        self.verticalLayout_5.addWidget(self.cb_frequency_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.browseFolder_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.browseFolder_6.setObjectName("browseFolder_6")
        self.verticalLayout_6.addWidget(self.browseFolder_6)
        self.browseFolder_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.browseFolder_5.setObjectName("browseFolder_5")
        self.verticalLayout_6.addWidget(self.browseFolder_5)
        self.saveCsv_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.saveCsv_3.setObjectName("saveCsv_3")
        self.verticalLayout_6.addWidget(self.saveCsv_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.line = QtWidgets.QFrame(self.splitter_2)
        self.line.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.GainCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.GainCheckBox.setObjectName("GainCheckBox")
        self.verticalLayout_12.addWidget(self.GainCheckBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.cb_Gain_1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_Gain_1.setMinimumSize(QtCore.QSize(81, 20))
        self.cb_Gain_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_Gain_1.setObjectName("cb_Gain_1")
        self.horizontalLayout_7.addWidget(self.cb_Gain_1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cb_Gain_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_Gain_2.setMinimumSize(QtCore.QSize(81, 20))
        self.cb_Gain_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_Gain_2.setObjectName("cb_Gain_2")
        self.horizontalLayout_6.addWidget(self.cb_Gain_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.line_Gain_Output = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_Gain_Output.setMinimumSize(QtCore.QSize(81, 20))
        self.line_Gain_Output.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.line_Gain_Output.setObjectName("line_Gain_Output")
        self.verticalLayout_3.addWidget(self.line_Gain_Output)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_7.addWidget(self.graphicsView_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.normalize_3 = QtWidgets.QCheckBox(self.tab)
        self.normalize_3.setObjectName("normalize_3")
        self.gridLayout.addWidget(self.normalize_3, 0, 0, 1, 1)
        self.hold_3 = QtWidgets.QCheckBox(self.tab)
        self.hold_3.setObjectName("hold_3")
        self.gridLayout.addWidget(self.hold_3, 0, 1, 1, 1)
        self.clearBtn_4 = QtWidgets.QPushButton(self.tab)
        self.clearBtn_4.setObjectName("clearBtn_4")
        self.gridLayout.addWidget(self.clearBtn_4, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setMaximumSize(QtCore.QSize(52, 16))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setMaximumSize(QtCore.QSize(52, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setMaximumSize(QtCore.QSize(52, 16))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.line_med1 = QtWidgets.QLineEdit(self.tab_2)
        self.line_med1.setObjectName("line_med1")
        self.verticalLayout_10.addWidget(self.line_med1)
        self.line_med2 = QtWidgets.QLineEdit(self.tab_2)
        self.line_med2.setObjectName("line_med2")
        self.verticalLayout_10.addWidget(self.line_med2)
        self.line_perdas = QtWidgets.QLineEdit(self.tab_2)
        self.line_perdas.setObjectName("line_perdas")
        self.verticalLayout_10.addWidget(self.line_perdas)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.estimate_gain_1_btn = QtWidgets.QPushButton(self.tab_2)
        self.estimate_gain_1_btn.setMaximumSize(QtCore.QSize(75, 20))
        self.estimate_gain_1_btn.setObjectName("estimate_gain_1_btn")
        self.verticalLayout_11.addWidget(self.estimate_gain_1_btn)
        self.estimate_gain_2_btn = QtWidgets.QPushButton(self.tab_2)
        self.estimate_gain_2_btn.setMaximumSize(QtCore.QSize(75, 20))
        self.estimate_gain_2_btn.setObjectName("estimate_gain_2_btn")
        self.verticalLayout_11.addWidget(self.estimate_gain_2_btn)
        self.estimate_gain_3_btn = QtWidgets.QPushButton(self.tab_2)
        self.estimate_gain_3_btn.setMaximumSize(QtCore.QSize(75, 20))
        self.estimate_gain_3_btn.setObjectName("estimate_gain_3_btn")
        self.verticalLayout_11.addWidget(self.estimate_gain_3_btn)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.gainEstimateFrequency = QtWidgets.QComboBox(self.tab_2)
        self.gainEstimateFrequency.setObjectName("gainEstimateFrequency")
        self.verticalLayout_13.addWidget(self.gainEstimateFrequency)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.graphicsView_estimativa = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_estimativa.setObjectName("graphicsView_estimativa")
        self.gridLayout_8.addWidget(self.graphicsView_estimativa, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FrequencyPlotter"))
        self.label.setText(_translate("MainWindow", "Medições de Distância:"))
        self.label_2.setText(_translate("MainWindow", "Medições de Perda:"))
        self.browseFolder.setText(_translate("MainWindow", "Browse"))
        self.browseFolder_4.setText(_translate("MainWindow", "Browse"))
        self.label_freq.setText(_translate("MainWindow", "Frequências [GHz]:"))
        self.label_what_plot.setText(_translate("MainWindow", "Parâmetro:"))
        self.saveCsv.setText(_translate("MainWindow", "Salvar CSV"))
        self.normalize.setText(_translate("MainWindow", "Normalizar"))
        self.hold.setText(_translate("MainWindow", "Hold"))
        self.clearBtn_2.setText(_translate("MainWindow", "Limpar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diagRad), _translate("MainWindow", "Diagrama de Radiação"))
        self.label_13.setText(_translate("MainWindow", "Medição de Distância:"))
        self.browseFolder_2.setText(_translate("MainWindow", "Browse"))
        self.label_14.setText(_translate("MainWindow", "Frequências [GHz]:"))
        self.label_15.setText(_translate("MainWindow", "Available Values:"))
        self.saveCsv_2.setText(_translate("MainWindow", "Salvar CSV"))
        self.normalize_2.setText(_translate("MainWindow", "Normalize"))
        self.hold_2.setText(_translate("MainWindow", "Hold"))
        self.clearBtn_3.setText(_translate("MainWindow", "Limpar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dist), _translate("MainWindow", "Distância"))
        self.label_16.setText(_translate("MainWindow", "File:"))
        self.browseFolder_3.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.perdas), _translate("MainWindow", "Perdas"))
        self.label_3.setText(_translate("MainWindow", "Medições de Distância:"))
        self.label_4.setText(_translate("MainWindow", "Medições de Perda:"))
        self.label_freq_2.setText(_translate("MainWindow", "Frequências [GHz]:"))
        self.browseFolder_6.setText(_translate("MainWindow", "Browse"))
        self.browseFolder_5.setText(_translate("MainWindow", "Browse"))
        self.saveCsv_3.setText(_translate("MainWindow", "Salvar CSV"))
        self.GainCheckBox.setText(_translate("MainWindow", "Estimar Ganho"))
        self.label_5.setText(_translate("MainWindow", "Medição 1:"))
        self.label_6.setText(_translate("MainWindow", "Medição 2:"))
        self.label_7.setText(_translate("MainWindow", "Ganho Estimado:"))
        self.normalize_3.setText(_translate("MainWindow", "Normalizar"))
        self.hold_3.setText(_translate("MainWindow", "Hold"))
        self.clearBtn_4.setText(_translate("MainWindow", "Limpar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ganho"))
        self.label_8.setText(_translate("MainWindow", "Medição 1:"))
        self.label_9.setText(_translate("MainWindow", "Medição 2:"))
        self.label_12.setText(_translate("MainWindow", "Perdas:"))
        self.estimate_gain_1_btn.setText(_translate("MainWindow", "Browse"))
        self.estimate_gain_2_btn.setText(_translate("MainWindow", "Browse"))
        self.estimate_gain_3_btn.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "Frequência [GHz]:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Estimativa de Ganho"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
